# Konfigurace pro steps/01_ingest_spinoco
# Kopíruj do config.yaml a uprav podle potřeby

auth:
  api_base_url: "https://api.spinoco.com"
  token: "YOUR_SPINOCO_API_TOKEN"
  account_id: "71da9579-7730-11ee-9300-a3a8e273fd52"

fetch:
  page_size: 100
  since: null  # ISO timestamp pro backfill, null pro incr

retry:
  max_retry: 3
  delay_seconds: 5

download:
  concurrency: 2
  validate_ogg_header: true  # kontrola "OggS" na začátku souboru
  temp_suffix: ".partial"   # přípona pro dočasné soubory

logging:
  level: "INFO"
  format: "json"  # nebo "text"

output:
  # Relativní cesty k output/runs/<STEP_RUN_ID>/data/
  metadata_calls: "metadata_call_tasks.jsonl"
  metadata_recordings: "metadata_recordings.jsonl"
  audio_dir: "audio/"

# Test mode - nastav na false pro skutečný API
test_mode: false
